version: '2'

services:
  gameloanmanagerweb:
    image: miguelpatreze/gameloanmanagerweb:1.3
    ports:
      - 4200:80
    depends_on:
      - identityserver
  identityserver:
    image: miguelpatreze/identityserver:1.1
    ports:
      - 82:80
    environment:
      MongoSettings__ConnectionString: mongodb://mongo:27017
      RedisSettings__ConnectionString: redis
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - 6379:6379
  redis:
    image: redis
    ports:
      - 27017:27017