version: '2'

services:
  gameloanmanagerweb:
    image: miguelpatreze/gameloanmanagerweb:1.7
    ports:
      - 4200:80
    depends_on:
      - identityserver
      - gameloanmanagerapi
  gameloanmanagerapi:
    image: miguelpatreze/gameloanmanagerapi:1.1
    ports:
      - 83:80
    depends_on:
      - mongo
  identityserver:
    image: miguelpatreze/identityserver:1.3
    ports:
      - 82:80
    environment:
      MongoSettings__ConnectionString: mongodb://mongo:27017
      RedisSettings__ConnectionString: redis
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
  redis:
    image: redis