version: '2'

services:
  gameloanmanagerweb:
    image: miguelpatreze/gameloanmanagerweb
    ports:
      - 4200:80
    depends_on:
      - gameloanmanageridentity
      - gameloanmanagerapi
  gameloanmanagerapi:
    image: miguelpatreze/gameloanmanagerapi
    ports:
      - 83:80
    environment:
      MongoSettings__ConnectionString: mongodb://mongo:27017
      IdentityServerSettings__Url: http://gameloanmanageridentity
    depends_on:
      - mongo
      - gameloanmanageridentity
  gameloanmanageridentity:
    image: miguelpatreze/gameloanmanageridentity
    ports:
      - 82:80
    environment:
      SqlServerSettings__ConnectionString: Server=sqlserver;Database=IdentityServer;User ID=sa;Password=Password123;
      RedisSettings__ConnectionString: redis
      Issuer_Uri: http://localhost:82
    depends_on:
      - sqlserver
      - redis
  mongo:
    image: mongo
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123
  redis:
    image: redis